# Generated by Django 5.2.7 on 2025-10-18 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя', validators=[django.core.validators.MaxLengthValidator], verbose_name='Имя')),
                ('surname', models.CharField(help_text='Введите фамилию', verbose_name='Фамилия')),
                ('age', models.SmallIntegerField(blank=True, help_text='Введите возраст', null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст')),
                ('sex', models.CharField(choices=[('f', 'Женщина'), ('m', 'Мужчина')], verbose_name='Пол')),
                ('active', models.BooleanField(verbose_name='Обучается')),
            ],
        ),
    ]
