# Generated by Django 5.2.7 on 2025-10-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Введите имя', verbose_name='Имя'),
        ),
    ]
