# Generated by Django 5.2.7 on 2025-10-18 13:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('py', 'Python'), ('c#', 'C#'), ('js', 'JavaScript')], verbose_name='Язык программирования')),
                ('course_num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Номер курса')),
                ('start_date', models.DateField(verbose_name='Начало курса')),
                ('end_date', models.DateField(verbose_name='Окончание курса')),
                ('description', models.TextField(blank=True, verbose_name='Описание курса')),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['surname'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, to='main.course', verbose_name='Посещаемые курсы'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('date', models.DateField(null=True, verbose_name='Дата получения')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='КУрс')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.student', verbose_name='Оценка студента')),
            ],
        ),
    ]
