# Generated by Django 5.2.7 on 2025-10-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_alter_student_options_student_course_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='phontos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['surname'], name='main_studen_surname_307540_idx'),
        ),
    ]
