# Generated by Django 5.2.7 on 2025-10-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_photo_student_main_studen_surname_307540_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='main_studen_surname_307540_idx',
        ),
    ]
